# Project information
site_name: Zib-transitie
site_description: Afspraken over modellering van zibs en toepassing in informatiestandaarden, systemen en processen.
site_author: Nictiz
site_url: https://www.zibtransitie.nl/

# Repository
repo_url: https://github.com/nictiz/zib-transitie-docs
edit_uri: blob/main/docs/

# Copyright
copyright: >-
  Copyright &copy; 2025 Nictiz | <a href="#__consent">Cookie-instellingen wijzigen</a> |
  <a href="https://nictiz.nl/privacy-statement" target="_blank" rel="noopener">Privacy statement</a>

# Configuration
theme:
  name: material
  language: nl
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Donkere modus
      primary: deep orange
      accent: deep orange
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Lichte modus
      primary: deep orange
      accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - toc.follow
  font:
    text: Roboto
    code: JetBrains Mono

# Plugins
plugins:
  - search
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: nictiz/zib-transitie-docs
      branch: main

# Additional configuration
extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    title: Toestemming voor cookies
    description: >-
      We gebruiken cookies om uw herhaalde bezoeken en voorkeuren te herkennen, om de effectiviteit van onze
      documentatie te meten en om na te gaan of gebruikers vinden wat ze zoeken. Met uw toestemming helpt u ons om onze
      documentatie te verbeteren.
  analytics:
    provider: google
    property: G-Q5LWKZTYLC
    feedback:
      title: Was deze pagina nuttig?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Deze pagina was nuttig
          data: 1
          note: >-
            Bedankt voor uw feedback!
        - icon: material/emoticon-sad-outline
          name: Deze pagina kan worden verbeterd
          data: 0
          note: >-
            Bedankt voor uw feedback! Help ons deze pagina te verbeteren door
            <a href="https://docs.google.com/forms/d/e/1FAIpQLSfL8so_NJBLjf3Z6AMrzN1JwqpCCuFnvZmeOjxfbtbTGbgPbg/viewform?entry.816166561={url}" target="_blank" rel="noopener">ons te vertellen wat u mist</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nictiz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/nictiz/

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Page tree
nav:
  - Home:
    - index.md
    - Nictiz: nictiz.md
  - FAQ:
    - faq/zib-transitie.md
    - Zibs - Algemeen: faq/zibs-algemeen.md
    - Zibs - Beheer: faq/zibs-beheer.md
    - Zibs - Inhoud en toepassing: faq/zibs-inhoud-en-toepassing.md
  - Blog:
    - blog/index.md