authors:
  arjanvanbremen:
    name: Arjan van Bremen
    description: Projectmanager
    avatar: https://avatars.githubusercontent.com/u/25454736
    url: https://github.com/avanbremen
  gerdameijboom:
    name: Gerda Meijboom
    description: Informatiearchitect
    avatar: https://avatars.githubusercontent.com/u/126160027
    url: https://github.com/GerdaMeijboom